site_name: BitMad
theme:
  name: material
  logo: assets/bmlogo.png
  features:
    - navigation.expand
  palette:
    scheme: slate 
copyright: Copyright &copy; 2024 BitMad

nav:
  - Home: index.md
  - Articles:
      - C64:
          - blog/C64intro.md
          - blog/C64PSU.md
          - blog/C64ASMCLS.md
          - blog/snappytmp.md
      - MiSTer FPGA:
          - blog/Misterbuild.md    
  - Documents:
      - manuals/index.md
      - manuals/SS5.md
#      - subtopic:
#          - blog/subtopic/boring_post.md
#          - blog/subtopic/interesting_post.md
extra:
  social:
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/BitMadcouk/
    - icon: fontawesome/brands/github
      link: https://github.com/BitMadcouk
    - icon: fontawesome/solid/envelope
      link: mailto:bitmad@bitmad.co.uk
  analytics:
    provider: google
    property: G-K79FGK7JXK

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
